export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as HomePage } from './Homepage';
export { default as WhatsWe } from './WhatsWe';
export { default as Services } from './Services';
export { default as Contact } from './Contact';
export { default as Careers } from './Careers';
export { default as CareersDetails } from './CareersDetails';
export { default as Feeds } from './Feeds';